// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoTraffic.Api.Infrastructure.Data;

#nullable disable

namespace PoTraffic.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PoTrafficDbContext))]
    [Migration("20260220010731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("FirstPollAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHolidayExcluded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPollAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PollCount")
                        .HasColumnType("int");

                    b.Property<int>("QuotaConsumed")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "SessionDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MonitoringSessions_RouteId_SessionDate");

                    b.ToTable("MonitoringSessions");
                });

            modelBuilder.Entity("MonitoringWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("DaysOfWeekMask")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("MonitoringWindows");
                });

            modelBuilder.Entity("PollRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRerouted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawProviderResponse")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TravelDurationSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolledAt")
                        .HasDatabaseName("IX_PollRecords_PolledAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_PollRecords_SessionId");

                    b.HasIndex("RouteId", "PolledAt")
                        .HasDatabaseName("IX_PollRecords_RouteId_PolledAt");

                    b.ToTable("PollRecords");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "HolidayDate")
                        .IsUnique()
                        .HasDatabaseName("UX_PublicHolidays_Locale_Date");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DestinationCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HangfireJobChainId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonitoringStatus")
                        .HasColumnType("int");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MonitoringStatus")
                        .HasDatabaseName("IX_Routes_UserId_MonitoringStatus");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SystemConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Key = "cost.perpoll.googlemaps",
                            Description = "Cost per poll - Google Maps",
                            IsSensitive = false,
                            Value = "0.005"
                        },
                        new
                        {
                            Key = "cost.perpoll.tomtom",
                            Description = "Cost per poll - TomTom",
                            IsSensitive = false,
                            Value = "0.004"
                        },
                        new
                        {
                            Key = "quota.daily.default",
                            Description = "Default daily session quota per user",
                            IsSensitive = false,
                            Value = "10"
                        },
                        new
                        {
                            Key = "quota.reset.utc",
                            Description = "Quota reset time (UTC)",
                            IsSensitive = false,
                            Value = "00:00"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGdprDeleteRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Projections.BaselineSlotDto", b =>
                {
                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MeanDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.Property<double?>("StdDevDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("TimeSlotBucket")
                        .HasColumnType("int");

                    b.ToTable("BaselineSlots");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Projections.UserDailyUsageDto", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TodayPollCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("UserDailyUsages");
                });

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("Sessions")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MonitoringWindow", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("Windows")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PollRecord", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("PollRecords")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MonitoringSession", "Session")
                        .WithMany("PollRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Route");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.Navigation("PollRecords");
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.Navigation("PollRecords");

                    b.Navigation("Sessions");

                    b.Navigation("Windows");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
