// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoTraffic.Api.Infrastructure.Data;

#nullable disable

namespace PoTraffic.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PoTrafficDbContext))]
    [Migration("20260221183331_AddTripleTestEntities")]
    partial class AddTripleTestEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("FirstPollAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsHolidayExcluded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPollAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PollCount")
                        .HasColumnType("int");

                    b.Property<int>("QuotaConsumed")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "SessionDate")
                        .IsUnique()
                        .HasDatabaseName("IX_MonitoringSessions_RouteId_SessionDate");

                    b.ToTable("MonitoringSessions");
                });

            modelBuilder.Entity("MonitoringWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("DaysOfWeekMask")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("MonitoringWindows");
                });

            modelBuilder.Entity("PollRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRerouted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("PolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawProviderResponse")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TravelDurationSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolledAt")
                        .HasDatabaseName("IX_PollRecords_PolledAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_PollRecords_SessionId");

                    b.HasIndex("RouteId", "PolledAt")
                        .HasDatabaseName("IX_PollRecords_RouteId_PolledAt");

                    b.ToTable("PollRecords");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "HolidayDate")
                        .IsUnique()
                        .HasDatabaseName("UX_PublicHolidays_Locale_Date");

                    b.ToTable("PublicHolidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HolidayDate = new DateOnly(2025, 1, 1),
                            HolidayName = "New Year's Day",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 2,
                            HolidayDate = new DateOnly(2025, 2, 3),
                            HolidayName = "St. Brigid's Day",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 3,
                            HolidayDate = new DateOnly(2025, 3, 17),
                            HolidayName = "St. Patrick's Day",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 4,
                            HolidayDate = new DateOnly(2025, 4, 21),
                            HolidayName = "Easter Monday",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 5,
                            HolidayDate = new DateOnly(2025, 5, 5),
                            HolidayName = "May Bank Holiday",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 6,
                            HolidayDate = new DateOnly(2025, 6, 2),
                            HolidayName = "June Bank Holiday",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 7,
                            HolidayDate = new DateOnly(2025, 8, 4),
                            HolidayName = "August Bank Holiday",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 8,
                            HolidayDate = new DateOnly(2025, 10, 27),
                            HolidayName = "October Bank Holiday",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 9,
                            HolidayDate = new DateOnly(2025, 12, 25),
                            HolidayName = "Christmas Day",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 10,
                            HolidayDate = new DateOnly(2025, 12, 26),
                            HolidayName = "St. Stephen's Day",
                            Locale = "en-IE"
                        },
                        new
                        {
                            Id = 11,
                            HolidayDate = new DateOnly(2025, 1, 1),
                            HolidayName = "New Year's Day",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 12,
                            HolidayDate = new DateOnly(2025, 4, 18),
                            HolidayName = "Good Friday",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 13,
                            HolidayDate = new DateOnly(2025, 4, 21),
                            HolidayName = "Easter Monday",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 14,
                            HolidayDate = new DateOnly(2025, 5, 5),
                            HolidayName = "Early May Bank Holiday",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 15,
                            HolidayDate = new DateOnly(2025, 5, 26),
                            HolidayName = "Spring Bank Holiday",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 16,
                            HolidayDate = new DateOnly(2025, 8, 25),
                            HolidayName = "Summer Bank Holiday",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 17,
                            HolidayDate = new DateOnly(2025, 12, 25),
                            HolidayName = "Christmas Day",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 18,
                            HolidayDate = new DateOnly(2025, 12, 26),
                            HolidayName = "Boxing Day",
                            Locale = "en-GB"
                        },
                        new
                        {
                            Id = 19,
                            HolidayDate = new DateOnly(2025, 1, 1),
                            HolidayName = "Neujahrstag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 20,
                            HolidayDate = new DateOnly(2025, 4, 18),
                            HolidayName = "Karfreitag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 21,
                            HolidayDate = new DateOnly(2025, 4, 21),
                            HolidayName = "Ostermontag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 22,
                            HolidayDate = new DateOnly(2025, 5, 1),
                            HolidayName = "Tag der Arbeit",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 23,
                            HolidayDate = new DateOnly(2025, 5, 29),
                            HolidayName = "Christi Himmelfahrt",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 24,
                            HolidayDate = new DateOnly(2025, 6, 9),
                            HolidayName = "Pfingstmontag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 25,
                            HolidayDate = new DateOnly(2025, 10, 3),
                            HolidayName = "Tag der Deutschen Einheit",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 26,
                            HolidayDate = new DateOnly(2025, 12, 25),
                            HolidayName = "1. Weihnachtstag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 27,
                            HolidayDate = new DateOnly(2025, 12, 26),
                            HolidayName = "2. Weihnachtstag",
                            Locale = "de-DE"
                        },
                        new
                        {
                            Id = 28,
                            HolidayDate = new DateOnly(2025, 1, 1),
                            HolidayName = "Jour de l'An",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 29,
                            HolidayDate = new DateOnly(2025, 4, 21),
                            HolidayName = "Lundi de Pâques",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 30,
                            HolidayDate = new DateOnly(2025, 5, 1),
                            HolidayName = "Fête du Travail",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 31,
                            HolidayDate = new DateOnly(2025, 5, 8),
                            HolidayName = "Victoire 1945",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 32,
                            HolidayDate = new DateOnly(2025, 5, 29),
                            HolidayName = "Ascension",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 33,
                            HolidayDate = new DateOnly(2025, 6, 9),
                            HolidayName = "Lundi de Pentecôte",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 34,
                            HolidayDate = new DateOnly(2025, 7, 14),
                            HolidayName = "Fête Nationale",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 35,
                            HolidayDate = new DateOnly(2025, 8, 15),
                            HolidayName = "Assomption",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 36,
                            HolidayDate = new DateOnly(2025, 11, 1),
                            HolidayName = "Toussaint",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 37,
                            HolidayDate = new DateOnly(2025, 11, 11),
                            HolidayName = "Armistice",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 38,
                            HolidayDate = new DateOnly(2025, 12, 25),
                            HolidayName = "Noël",
                            Locale = "fr-FR"
                        },
                        new
                        {
                            Id = 39,
                            HolidayDate = new DateOnly(2025, 1, 1),
                            HolidayName = "New Year's Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 40,
                            HolidayDate = new DateOnly(2025, 1, 20),
                            HolidayName = "Martin Luther King Jr. Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 41,
                            HolidayDate = new DateOnly(2025, 2, 17),
                            HolidayName = "Presidents' Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 42,
                            HolidayDate = new DateOnly(2025, 5, 26),
                            HolidayName = "Memorial Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 43,
                            HolidayDate = new DateOnly(2025, 6, 19),
                            HolidayName = "Juneteenth",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 44,
                            HolidayDate = new DateOnly(2025, 7, 4),
                            HolidayName = "Independence Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 45,
                            HolidayDate = new DateOnly(2025, 9, 1),
                            HolidayName = "Labor Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 46,
                            HolidayDate = new DateOnly(2025, 11, 11),
                            HolidayName = "Veterans Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 47,
                            HolidayDate = new DateOnly(2025, 11, 27),
                            HolidayName = "Thanksgiving Day",
                            Locale = "en-US"
                        },
                        new
                        {
                            Id = 48,
                            HolidayDate = new DateOnly(2025, 12, 25),
                            HolidayName = "Christmas Day",
                            Locale = "en-US"
                        });
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DestinationCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HangfireJobChainId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonitoringStatus")
                        .HasColumnType("int");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MonitoringStatus")
                        .HasDatabaseName("IX_Routes_UserId_MonitoringStatus");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SystemConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            Key = "cost.perpoll.googlemaps",
                            Description = "Cost per poll - Google Maps",
                            IsSensitive = false,
                            Value = "0.005"
                        },
                        new
                        {
                            Key = "cost.perpoll.tomtom",
                            Description = "Cost per poll - TomTom",
                            IsSensitive = false,
                            Value = "0.004"
                        },
                        new
                        {
                            Key = "quota.daily.default",
                            Description = "Default daily session quota per user",
                            IsSensitive = false,
                            Value = "10"
                        },
                        new
                        {
                            Key = "quota.reset.utc",
                            Description = "Quota reset time (UTC)",
                            IsSensitive = false,
                            Value = "00:00"
                        });
                });

            modelBuilder.Entity("TripleTestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DestinationCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TripleTestSessions");
                });

            modelBuilder.Entity("TripleTestShot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("DistanceMetres")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<int>("OffsetSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ShotIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_TripleTestShots_SessionId_ShotIndex");

                    b.ToTable("TripleTestShots");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGdprDeleteRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Projections.BaselineSlotDto", b =>
                {
                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MeanDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int");

                    b.Property<double?>("StdDevDurationSeconds")
                        .HasColumnType("float");

                    b.Property<int>("TimeSlotBucket")
                        .HasColumnType("int");

                    b.ToTable("BaselineSlots");
                });

            modelBuilder.Entity("PoTraffic.Api.Infrastructure.Data.Projections.UserDailyUsageDto", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TodayPollCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("UserDailyUsages");
                });

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("Sessions")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MonitoringWindow", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("Windows")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PollRecord", b =>
                {
                    b.HasOne("EntityRoute", "Route")
                        .WithMany("PollRecords")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MonitoringSession", "Session")
                        .WithMany("PollRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Route");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripleTestShot", b =>
                {
                    b.HasOne("TripleTestSession", "Session")
                        .WithMany("Shots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MonitoringSession", b =>
                {
                    b.Navigation("PollRecords");
                });

            modelBuilder.Entity("EntityRoute", b =>
                {
                    b.Navigation("PollRecords");

                    b.Navigation("Sessions");

                    b.Navigation("Windows");
                });

            modelBuilder.Entity("TripleTestSession", b =>
                {
                    b.Navigation("Shots");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
