<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PoTraffic.E2EUI</RootNamespace>
    <AssemblyName>PoTraffic.E2EUI</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PoTraffic.Shared\PoTraffic.Shared.csproj" />
    <ProjectReference Include="..\..\src\PoTraffic.Api\PoTraffic.Api.csproj" />
    <ProjectReference Include="..\..\src\PoTraffic.Client\PoTraffic.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <!-- Playwright .NET C# for E2E tests -->
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
